// 도타2 길드원 상세 스탯
const dota2GuildMembers = [
    {
        id: 1,
        name: "달돌",
        mainRole: "캐리",
        subRole: "미드", 
        favoriteHeroes: ["레슈락", "슬라크", "흡혈마"],
        mmr: 3500,
        winRate: "56.7%",
        kda: 3.4,
        gpm: 580,
        xpm: 620,
        lastPlayed: "2024-01-20",
        partyAttendance: "92%",
        heroPool: 28,
        communication: "보이스챗 활발",
        playStyle: "공격적",
        strength: "라인전, 후반 캐리력",
        weakness: "위치선정 가끔 실수"
    },
    {
        id: 2,
        name: "오야",
        mainRole: "하드서포트",
        subRole: "오프",
        favoriteHeroes: ["마르스", "드로우", "디스럽터"],
        mmr: 4320,
        winRate: "53.2%",
        kda: 2.9,
        gpm: 310,
        xpm: 390,
        lastPlayed: "2024-01-19",
        partyAttendance: "95%",
        heroPool: 22,
        communication: "맵 ping 활발",
        playStyle: "안정적",
        strength: "와딩, 로션조율",
        weakness: "한타 집중력"
    },
    {
        id: 3,
        name: "황군",
        mainRole: "오프",
        subRole: "캐리",
        favoriteHeroes: ["엑스", "퍼지", "네퓨"],
        mmr: 3700,
        winRate: "55.1%",
        kda: 3.1,
        gpm: 520,
        xpm: 560,
        lastPlayed: "2024-01-18",
        partyAttendance: "88%",
        heroPool: 25,
        communication: "보이스챗 활발",
        playStyle: "공격적",
        strength: "이니시에이팅",
        weakness: "가끔 오버확신"
    },
    {
        id: 4,
        name: "고무",
        mainRole: "하드서포트",
        subRole: "오프",
        favoriteHeroes: ["디스럽터", "타헌", "다크시어"],
        mmr: 3980,
        winRate: "51.8%",
        kda: 2.7,
        gpm: 290,
        xpm: 370,
        lastPlayed: "2024-01-20",
        partyAttendance: "90%",
        heroPool: 19,
        communication: "조용함",
        playStyle: "방어적",
        strength: "생존력, 아군 보호",
        weakness: "공격적 플레이 부족"
    },
    {
        id: 5,
        name: "도외",
        mainRole: "하드서포트",
        subRole: "서포트",
        favoriteHeroes: ["템플러 어쌔신", "퍽", "스톰 스피릿"],
        mmr: 5120,
        winRate: "58.3%",
        kda: 3.6,
        gpm: 610,
        xpm: 650,
        lastPlayed: "2024-01-19",
        partyAttendance: "85%",
        heroPool: 30,
        communication: "보이스챗 활발",
        playStyle: "공격적",
        strength: "개인기량, 한타 집중력",
        weakness: "팀플레이 약간 부족"
    },
    {
        id: 6,
        name: "똥빨",
        mainRole: "서포트",
        subRole: "미드",
        favoriteHeroes: ["퍼그나", "오디", "스레메"],
        mmr: 3913,
        winRate: "50.5%",
        kda: 2.5,
        gpm: 280,
        xpm: 350,
        lastPlayed: "2024-01-17",
        partyAttendance: "78%",
        heroPool: 16,
        communication: "맵 ping 활발",
        playStyle: "보조형",
        strength: "아이템 활용",
        weakness: "초반 라인전"
    },
    {
        id: 7,
        name: "와쿨",
        mainRole: "하드서포트",
        subRole: "서포트",
        favoriteHeroes: ["클락", "디럽", "크메"],
        mmr: 4450,
        winRate: "54.2%",
        kda: 3.0,
        gpm: 510,
        xpm: 540,
        lastPlayed: "2024-01-20",
        partyAttendance: "91%",
        heroPool: 24,
        communication: "보이스챗 활발",
        playStyle: "밸런스",
        strength: "다양한 역할 수행",
        weakness: "특정 상황 대처"
    },
    {
        id: 8,
        name: "건더",
        mainRole: "하드서포트",
        subRole: "서포트",
        favoriteHeroes: ["위닥", "언다잉", "베놈"],
        mmr: 4210,
        winRate: "52.9%",
        kda: 2.8,
        gpm: 320,
        xpm: 410,
        lastPlayed: "2024-01-18",
        partyAttendance: "89%",
        heroPool: 21,
        communication: "채팅 활발",
        playStyle: "공격적 서포트",
        strength: "한타 기여도",
        weakness: "위치선정"
    },
    {
        id: 9,
        name: "로떼",
        mainRole: "미드",
        subRole: "서포트",
        favoriteHeroes: ["레슈락", "오디", "영파"],
        mmr: 4680,
        winRate: "55.5%",
        kda: 3.3,
        gpm: 590,
        xpm: 610,
        lastPlayed: "2024-01-19",
        partyAttendance: "87%",
        heroPool: 26,
        communication: "보이스챗 활발",
        playStyle: "안정적",
        strength: "CS, 아이템 타이밍",
        weakness: "극한상황 대처"
    },
    {
        id: 10,
        name: "팽돌",
        mainRole: "하드서포트",
        subRole: "캐리",
        favoriteHeroes: ["메두사", "악령", "클링츠"],
        mmr: 2736,
        winRate: "57.1%",
        kda: 3.5,
        gpm: 600,
        xpm: 630,
        lastPlayed: "2024-01-20",
        partyAttendance: "93%",
        heroPool: 27,
        communication: "보이스챗 활발",
        playStyle: "공격적",
        strength: "라인전, 로밍",
        weakness: "후반 결정력"
    },
    {
        id: 11,
        name: "나즈린",
        mainRole: "캐리",
        subRole: "미드",
        favoriteHeroes: ["스나", "망령", "저거넛"],
        mmr: 4080,
        winRate: "52.0%",
        kda: 2.6,
        gpm: 300,
        xpm: 380,
        lastPlayed: "2024-01-17",
        partyAttendance: "84%",
        heroPool: 20,
        communication: "조용함",
        playStyle: "전략적",
        strength: "스킬 활용도",
        weakness: "정신력"
    },
    {
        id: 12,
        name: "신양",
        mainRole: "캐리",
        subRole: "미드",
        favoriteHeroes: ["워든", "크메", "오거"],
        mmr: 4611,
        winRate: "54.8%",
        kda: 3.2,
        gpm: 530,
        xpm: 570,
        lastPlayed: "2024-01-19",
        partyAttendance: "90%",
        heroPool: 23,
        communication: "맵 ping 활발",
        playStyle: "밸런스",
        strength: "객기, 팀파이트",
        weakness: "라인전 변동성"
    },
    {
        id: 13,
        name: "미유",
        mainRole: "오프",
        subRole: "서포트",
        favoriteHeroes: ["마르스", "던브", "닥시"],
        mmr: 2000,
        winRate: "51.5%",
        kda: 2.7,
        gpm: 295,
        xpm: 365,
        lastPlayed: "2024-01-18",
        partyAttendance: "86%",
        heroPool: 18,
        communication: "채팅 활발",
        playStyle: "방어적",
        strength: "아군 보호, 로션",
        weakness: "공격적 플레이"
    }
];

// 각 길드원별 육각형 스탯 (1-10점)
const memberStats = {
    "달돌": { laning: 8, teamfight: 7, objective: 6, survival: 7, farming: 9, leadership: 5 },
    "오야": { laning: 6, teamfight: 8, objective: 7, survival: 6, farming: 4, leadership: 8 },
    "황군": { laning: 7, teamfight: 9, objective: 8, survival: 6, farming: 7, leadership: 7 },
    "고무": { laning: 5, teamfight: 6, objective: 5, survival: 8, farming: 3, leadership: 6 },
    "도외": { laning: 9, teamfight: 8, objective: 7, survival: 6, farming: 9, leadership: 4 },
    "똥빨": { laning: 4, teamfight: 5, objective: 6, survival: 5, farming: 3, leadership: 5 },
    "와쿨": { laning: 7, teamfight: 7, objective: 7, survival: 7, farming: 7, leadership: 7 },
    "건더": { laning: 6, teamfight: 8, objective: 6, survival: 5, farming: 4, leadership: 7 },
    "로떼": { laning: 8, teamfight: 7, objective: 6, survival: 8, farming: 8, leadership: 6 },
    "팽돌": { laning: 9, teamfight: 8, objective: 8, survival: 6, farming: 8, leadership: 7 },
    "나즈린": { laning: 5, teamfight: 6, objective: 7, survival: 4, farming: 3, leadership: 5 },
    "신양": { laning: 7, teamfight: 8, objective: 7, survival: 7, farming: 6, leadership: 6 },
    "미유": { laning: 5, teamfight: 5, objective: 6, survival: 7, farming: 3, leadership: 6 }
};

// 기존 데이터에 스탯 통합
dota2GuildMembers.forEach(member => {
    if (memberStats[member.name]) {
        member.stats = memberStats[member.name];
    }
});

// 도타2 히어로 영어 이름 매핑
const heroNameMapping = {
    "안메": "antimage",
    "저거넛": "juggernaut", 
    "팬어": "phantom_assassin",
    "템어": "templar_assassin",
    "키오라": "keeper_of_the_light",
    "위버": "weaver",
    "라이온": "lion",
    "던브": "dawnbreaker",
    "리전": "legion_commander",
    "슬라크": "slark",
    "아바돈": "abaddon",
    "오거": "ogre_magi",
    "디럽": "disruptor",
    "퍽": "puck",
    "스톰": "storm_spirit",
    "고영": "ancient_apparition",
    "레슈락": "leshrac",
    "터스크": "tusk",
    "엠버": "ember_spirit",
    "마르스": "mars",
    "벤지": "vengeful_spirit",
    "대지령": "earth_spirit",
    "스냅": "snapfire",
    "윈와": "winter_wyvern",
    "리나": "lina",
    "클링츠": "clinkz",
    "메두사": "medusa",
    "드나": "dragon_knight",
    "퀸오페": "queenofpain",
    "바이퍼": "viper",
    "쉐데": "shadow_demon",
    "에니그마": "enigma",
    "타이니": "tiny",
    "슬라다": "slardar",
    "네크로": "necrophos",
    "크메": "crystal_maiden"
};

// 히어로 이미지 URL 생성 함수
function getHeroImageUrl(heroName) {
    const englishName = heroNameMapping[heroName] || 'antimage';
    return `https://cdn.dota2.com/apps/dota2/images/heroes/${englishName}_sb.png`;
}